os: linux
services:
   - docker
sudo: required
language: python
env:
  global:
    - CONAN_REFERENCE="Catch/1.9.2"
    - CONAN_USERNAME="uilianries"
    - CONAN_CHANNEL="ci"
    - CONAN_TOTAL_PAGES=1
    - CONAN_CURRENT_PAGE=1
    - CONAN_STABLE_BRANCH_PATTERN="release/*"
    - CONAN_UPLOAD="https://api.bintray.com/conan/uilianries/conan"

  matrix:
    - CONAN_GCC_VERSIONS=4.1 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=uilianries/conangcc41 CONAN_ARCHS=x86_64
    - CONAN_GCC_VERSIONS=4.6 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=5.4 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.2 CONAN_USE_DOCKER=1
    - CONAN_GCC_VERSIONS=6.3 CONAN_USE_DOCKER=1
    - CONAN_CLANG_VERSIONS=3.8 CONAN_USE_DOCKER=1
    - CONAN_CLANG_VERSIONS=3.9 CONAN_USE_DOCKER=1
    - CONAN_CLANG_VERSIONS=4.0 CONAN_USE_DOCKER=1

matrix:
   include:
       - os: osx
         osx_image: xcode8.2 # apple-clang 8.2
         language: generic
         env:
       - os: osx
         osx_image: xcode8.1 # apple-clang 8.1
         language: generic
         env:
       - os: osx
         osx_image: xcode8 # apple-clang 8.0
         language: generic
         env:
       - os: osx
         osx_image: xcode7.3 # apple-clang 7.3
         language: generic
         env:
       - os: osx
         osx_image: xcode7.1 # apple-clang 7.0
         language: generic
         env:
       - os: osx
         osx_image: xcode6.4 # apple-clang 6.1
         language: generic
         env:
       - os: osx
         osx_image: xcode6.2 # apple-clang 6.0
         language: generic
         env:

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
