env:
  global:
    - CONAN_REFERENCE: "Catch/1.9.6"

linux-job: &linux-job
    os: linux
    sudo: required
    language: python
    services:
      - docker
    python: "3.6"

osx-job: &osx-job
    os: osx
    language: generic

matrix:
    include:

    - <<: *linux-job
      env: CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=lasote/conangcc48

    - <<: *linux-job
      env: CONAN_GCC_VERSIONS=5.4 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=lasote/conangcc54

    - <<: *linux-job
      env: CONAN_GCC_VERSIONS=6.3 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=lasote/conangcc63

    - <<: *linux-job
      env: CONAN_CLANG_VERSIONS=3.9 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=lasote/conanclang39

    - <<: *linux-job
      env: CONAN_CLANG_VERSIONS=4.0 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=lasote/conanclang40

    - <<: *osx-job
      osx_image: xcode7.3
      env: CONAN_APPLE_CLANG_VERSIONS=7.3

    - <<: *osx-job
      osx_image: xcode8.2
      env: CONAN_APPLE_CLANG_VERSIONS=8.0

    - <<: *osx-job
      osx_image: xcode8.3
      env: CONAN_APPLE_CLANG_VERSIONS=8.1

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
